[package]
name = "ksite"
version = "0.6.0-alpha-23"
edition = "2021"

[profile.release]
# panic = "abort" # DO NOT USE THIS! cause tokio worker abort
strip = true
lto = "fat"
codegen-units = 1
# opt-level = "z"

# Best check speed, `cargo check --profile=ci`
[profile.ci]
inherits = "release"
opt-level = 0
lto = "off"
panic = "abort"
incremental = false
codegen-units = 256

# Best incremental build speed, less disk usage, `mold -run cargo run`
[profile.dev]
# debug = false # this switch disabled backtrace
panic = "abort"
[profile.dev.package."*"]
debug = false
strip = true
opt-level = "z"

[dependencies]
anyhow = "1"
askama_escape = "0.10"
axum = "0.6.0-rc.4"
flate2 = "1"
futures-core = "0.3"
httpdate = "1"
hyper = { version = "0.14", features = ["client", "http2"] }
hyper-rustls = { version = "0.23", default-features = false }
once_cell = "1"
rand = "0.8"
ricq = "=0.1.17" # unstable, fixed version here
rusqlite = { version = "0.28", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "fs"] }
tokio-rustls = "0.23"
tower = "0.4"
tower-http = { version = "0.3", features = ["auth"] }
webpki-roots = "0.22"
ring = "0.16"

[patch.crates-io]
ricq = { rev = "87ca76f", git = "https://github.com/lz1998/ricq" }
prost-build = { path = "src/crates/prost-gen" } # for `ricq-core`
tracing = { path = "src/crates/tracing-fake" }
