name: ci
on: [push, pull_request]
env:
  RUSTC_BOOTSTRAP: 1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo Check
        run: rustup show ; cargo check --profile=ci
